use_frameworks!

def sharedPods
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'
end

target 'TheMovieDB' do
    platform :ios, '10.0'
    pod 'OHHTTPStubs/Swift'
    sharedPods

  target 'TheMovieDBTests' do
    inherit! :search_paths
  end
end

target 'Watch Extension' do
  platform :watchos, '2.0'
  pod 'Alamofire', '~> 4.7'
end


#source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '10.0'
#use_frameworks!
#
#target '<Your Target Name>' do
#  pod 'AlamofireImage', '~> 3.5'
#end
